config/routes.rb
Rollout::Application.routes.draw do
  resources :logs

  resources :divisions

  resources :changes

  resources :launches

  resources :prices

  resources :clients

  root :to => "clients#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/client.rb
# == Schema Information
#
# Table name: clients
#
#  id                    :integer          not null, primary key
#  name                  :string(255)
#  division_id           :string(255)
#  region                :string(255)
#  created_at            :datetime
#  updated_at            :datetime
#  internal              :boolean
#  price_id              :integer
#  launch_date           :date
#  notes                 :text
#  billing_start_date    :date
#  consolidated          :boolean
#  finance_contact_name  :string(255)
#  finance_contact_email :string(255)
#  finance_contact_phone :string(255)
#  venue_contact_name    :string(255)
#  venue_contact_email   :string(255)
#  venue_contact_phone   :string(255)
#  ticketing_provider    :string(255)
#  kickoff_date          :date
#

class Client < ActiveRecord::Base
	belongs_to :price
  belongs_to :division
  has_paper_trail
  resourcify
	# has_one :launch - removing launch and just including in client db
	# has_one :division

  # def self.to_csv(options = {})
  #  CSV.generate(options) do |csv|
  #    csv << column_names
  #    all.each do |product|
  #      csv << product.attributes.values_at(*column_names)
  #    end
  #  end
  # end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction
  before_filter :authenticate_user!
  load_and_authorize_resource

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
    t = Time.zone.now
    @now = t.strftime("%a, %b %d, %Y, %l:%M %p")
    # @full_rev_2014 = 
    # @partial_rev_2015 = 0
    # @clients.each do |client|
    #     if client.billing_start_date.year == 2015
    #         calc = (((2016 * 12 + 1) - (client.billing_start_date.year * 12 + client.billing_start_date.month)) * client.price.cost)
    #         @partial_rev_2015 += calc
    #         calc
    #     end
    # end
    # @full_rev_2014 = 0
    # @clients.each do |client|
    #   if client.billing_start_date.year == 2014
    #     @full_rev_2014 = (client.price.cost * 12)
    #     # @full_rev_2014 += calc
    #     # calc
    #   end
    # end
    # @total_rev_2015 = (@full_rev_2014 + @partial_rev_2015)
    respond_to do |format|
      format.html
      format.json { render json: ClientsDatatable.new(view_context) }
      format.xls
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])
    @now = Time.now
  end

  # GET /clients/new
  def new
    @client = Client.new
    can? :create, @client
    @user = current_user
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
    @user = current_user
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)
    @user = current_user

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render action: 'show', status: :created, location: @client }
      else
        format.html { render action: 'new' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :billing_start_date, :kickoff_date, :ticketing_provider, :division_id, :region, :price_id, :internal, :launch_date, :notes)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<script type="text/javascript">
  $(function() {
    $('.date_picker').datetimepicker({
    });
  });
</script>

<%= simple_form_for(@client) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.association :division %>
    <%= f.input :ticketing_provider %>
    <%= f.input :region %>
    <%= f.input :kickoff_date, :as => :date_picker %>
    <%= f.input :launch_date, :as => :date_picker %>
    <%= f.input :billing_start_date, :as => :date_picker %>
    <%= f.input :internal %>
    <%= f.association :price %>
    <%= f.input :finance_contact_name %>
    <%= f.input :finance_contact_email %>
    <%= f.input :finance_contact_phone %>
    <%= f.input :venue_contact_name %>
    <%= f.input :venue_contact_email %>
    <%= f.input :venue_contact_phone %>
    <%= f.input :notes %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<!-- calculations for the 2014 & 2015 financial and count summary; ideally these would be more centralized so the calcs are available elsewhere, but this is the page need right now -->

<!-- new revenue in 2014 -->
<% partial_rev_2014 = 0 %>
<% @clients.each do |client| %>
    <% if client.billing_start_date.year == 2014 %>
        <% calc = (((2015 * 12 + 1) - (client.billing_start_date.year * 12 + client.billing_start_date.month)) * client.price.cost) %>
        <% partial_rev_2014 += calc %>
        <% calc %>
    <% end %>
<% end %>

<!-- new revenue in 2015 - not including any continuing 2014 clients -->
<% partial_rev_2015 = 0 %>
<% @clients.each do |client| %>
    <% if client.billing_start_date.year == 2015 %>
        <% calc = (((2016 * 12 + 1) - (client.billing_start_date.year * 12 + client.billing_start_date.month)) * client.price.cost) %>
        <% partial_rev_2015 += calc %>
        <% calc %>
    <% end %>
<% end %>

<!-- total revenue in 2014 - only a projection for calculation total 2015 revenue -->
<% full_rev_2014 = 0 %>
<% @clients.each do |client| %>
  <% if client.billing_start_date.year == 2014 %>
    <% calc = (client.price.cost * 12) %>
    <% full_rev_2014 += calc %>
    <% calc %>
  <% end %>
<% end %>



<!-- table for displaying the summary calcs from above -->

<div class="container">
<br>
<h1>Advantage Clients as of: <%= @now %> PST</h1> 

<div class="alert alert-info alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong>UPDATES: </strong> the rollout schedule <strong>WILL</strong> change, so please take everything with a grain of salt right now <strong>(Updated for draft rollout plan: Jul 28, 2014)</strong>
</div>

<table class="table table-striped table-hover">
<thead>
  <th>2014</th>
  <th>2015</th>
</thead>
<tbody>
  <tr>
    <td>Clients: <strong><%= Client.where("extract(year from launch_date) = ?", 2014).count %></strong></td>
    <td>Clients: <strong><%= Client.where("extract(year from launch_date) = ?", 2015).count %></strong></td>
  </tr>
  <tr>
    <td>2014 Revenue: <strong>$<%= number_with_delimiter(partial_rev_2014, :delimiter => ',') %></strong></td>
    <td>New Revenue in 2015: <strong>$<%= number_with_delimiter(partial_rev_2015, :delimiter => ',') %></strong></td>
  </tr>
  <tr>
    <td>2014 Revenue (if full year): <strong>$<%= number_with_delimiter(full_rev_2014, :delimiter => ',') %></strong></td>
    <td>Total Revenue in 2015: <strong>$<%= number_with_delimiter(full_rev_2014 + partial_rev_2015, :delimiter => ',') %></strong></td>
  </tr>
</tbody>
</table>

  <div class="btn-group"><% if can? :new, @client %>
    <button type="button" class="btn btn-default btn">
      <%= link_to 'New Client', new_client_path %>
    </button><% end %>
    <button type="button" class="btn btn-default btn">
      <%= link_to "Export XLS", clients_path(format: "xls") %>
    </button>
  <br>
  </div>
</div>


<!-- datatables framework below -->

<div class="container">
<table id="clients" class="display" data-source="<%= clients_url(format: "json") %>">
  <thead>
    <tr>
      <th>Client Name</th>
      <th>Kickoff Date</th>
      <th>Launch Date</th>
      <th>Billing Date</th>
      <th>Price Per Month</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>


<!-- only doug and jake can edit - revise models/ability.rb and the actual data to add more/other permissions or users to the admin bucket -->

<br>
<% if can? :new, @client %>
<%= link_to 'New Client', new_client_path %>
<% end %>
</div>

app/views/clients/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:o="urn:schemas-microsoft-com:office:office"
 xmlns:x="urn:schemas-microsoft-com:office:excel"
 xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:html="http://www.w3.org/TR/REC-html40">
 <DocumentProperties xmlns="urn:schemas-microsoft-com:office:office">
  <LastAuthor>Jake Levine</LastAuthor>
  <Created>2014-04-23T04:55:13Z</Created>
  <Version>14.0</Version>
 </DocumentProperties>
 <OfficeDocumentSettings xmlns="urn:schemas-microsoft-com:office:office">
  <AllowPNG/>
 </OfficeDocumentSettings>
 <ExcelWorkbook xmlns="urn:schemas-microsoft-com:office:excel">
  <WindowHeight>16080</WindowHeight>
  <WindowWidth>28800</WindowWidth>
  <WindowTopX>0</WindowTopX>
  <WindowTopY>0</WindowTopY>
  <ProtectStructure>False</ProtectStructure>
  <ProtectWindows>False</ProtectWindows>
 </ExcelWorkbook>
 <Styles>
  <Style ss:ID="Default" ss:Name="Normal">
   <Alignment ss:Vertical="Bottom"/>
   <Borders/>
   <Font ss:FontName="Calibri" x:Family="Swiss" ss:Size="12" ss:Color="#000000"/>
   <Interior/>
   <NumberFormat/>
   <Protection/>
  </Style>
  <Style ss:ID="s22">
   <NumberFormat ss:Format="yyyy\-mm\-dd"/>
  </Style>
 </Styles>
  <Worksheet ss:Name="Advantage Clients">
    <Table x:FullColumns="1"
     x:FullRows="1" ss:DefaultColumnWidth="65" ss:DefaultRowHeight="15">
     <Column ss:AutoFitWidth="0" ss:Width="227"/>
     <Column ss:AutoFitWidth="0" ss:Width="68"/>
     <Column ss:AutoFitWidth="0" ss:Width="68"/>
     <Column ss:AutoFitWidth="0" ss:Width="87"/>
     <Column ss:AutoFitWidth="0" ss:Width="103"/>
     <Column ss:AutoFitWidth="0" ss:Width="103"/>
     <Column ss:AutoFitWidth="0" ss:Width="66"/>
     <Column ss:AutoFitWidth="0" ss:Width="99"/>
     <Column ss:AutoFitWidth="0" ss:Width="99"/>
     <Column ss:AutoFitWidth="0" ss:Width="99"/>
     <Column ss:AutoFitWidth="0" ss:Width="99"/>
     <Column ss:AutoFitWidth="0" ss:Width="99" />
     <Column ss:AutoFitWidth="0" ss:Width="180" />
     <Column ss:AutoFitWidth="0" ss:Width="120" />
     <Column ss:AutoFitWidth="0" ss:Width="120" />
     <Column ss:AutoFitWidth="0" ss:Width="120" />
     <Column ss:AutoFitWidth="0" ss:Width="120" />
     <Column ss:AutoFitWidth="0" ss:Width="120" />
     <Column ss:AutoFitWidth="0" ss:Width="120" />
     <Column ss:AutoFitWidth="0" ss:Width="120" />
        <Row>
          <Cell><Data ss:Type="String">Name</Data></Cell>
          <Cell><Data ss:Type="String">Division</Data></Cell>
          <Cell><Data ss:Type="String">Ticketing Provider(s)</Data></Cell>
          <Cell><Data ss:Type="String">Region</Data></Cell>
          <Cell><Data ss:Type="String">Kickoff Date</Data></Cell>
          <Cell><Data ss:Type="String">Launch Date</Data></Cell>
          <Cell><Data ss:Type="String">Billing Start Date</Data></Cell>
          <Cell><Data ss:Type="String">Internal?</Data></Cell>
          <Cell><Data ss:Type="String">Business Unit Type</Data></Cell>
          <Cell><Data ss:Type="String">Cost Per Month</Data></Cell>
          <Cell><Data ss:Type="String"># of months in 2014</Data></Cell>
          <Cell><Data ss:Type="String">New Revenue in 2014</Data></Cell>
          <Cell><Data ss:Type="String"># of months in 2015</Data></Cell>
          <Cell><Data ss:Type="String">New Revenue in 2015</Data></Cell>
          <Cell><Data ss:Type="String">Total Revenue in 2015</Data></Cell>
          <Cell><Data ss:Type="String">Notes</Data></Cell>
          <Cell><Data ss:Type="String">Finance Contact Name</Data></Cell>
          <Cell><Data ss:Type="String">Finance Contact Email</Data></Cell>
          <Cell><Data ss:Type="String">Finance Contact Phone</Data></Cell>
          <Cell><Data ss:Type="String">Venue Contact Name</Data></Cell>
          <Cell><Data ss:Type="String">Venue Contact Email</Data></Cell>
          <Cell><Data ss:Type="String">Venue Contact Email</Data></Cell>
        </Row>
    <% @clients.each do |client| %>
        <Row>
          <Cell><Data ss:Type="String"><%= client.name %></Data></Cell>
          <Cell><Data ss:Type="String"><%= client.division.name %></Data></Cell>
          <Cell><Data ss:Type="String"><%= client.ticketing_provider %></Data></Cell>
          <Cell><Data ss:Type="String"><%= client.region %></Data></Cell>
          <Cell ss:StyleID="s22"><Data ss:Type="DateTime"><%= client.kickoff_date %></Data></Cell>
          <Cell ss:StyleID="s22"><Data ss:Type="DateTime"><%= client.launch_date %></Data></Cell>
          <Cell ss:StyleID="s22"><Data ss:Type="DateTime"><%= client.billing_start_date %></Data></Cell>
          <Cell><Data ss:Type="String"><%= client.internal %></Data></Cell>
          <Cell><Data ss:Type="String"><%= client.price.name %></Data></Cell>
          <Cell><Data ss:Type="Number"><%= client.price.cost %></Data></Cell>
          <Cell><Data ss:Type="Number"><% if (client.billing_start_date.year == 2014) %><%= ((2015 * 12 + 1) - (client.billing_start_date.year * 12 + client.billing_start_date.month)) %><% end %></Data></Cell>
          <Cell><Data ss:Type="Number"><% partial_rev_2014 = 0 %><% if client.billing_start_date.year == 2014 %><% calc = (((2015 * 12 + 1) - (client.billing_start_date.year * 12 + client.billing_start_date.month)) * client.price.cost) %><% partial_rev_2014 += calc %><% calc %><% end %><% if (client.billing_start_date.year == 2014) %><%= (partial_rev_2014) %><% end %></Data></Cell>
          <Cell><Data ss:Type="Number"><% if client.billing_start_date.year == 2014 %><%= 12 %><% elsif client.billing_start_date.year == 2015 %><%= ((2016 * 12 + 1) - (client.billing_start_date.year * 12 + client.billing_start_date.month)) %><% end %></Data></Cell>
          <Cell><Data ss:Type="Number"><% partial_rev_2015 = 0 %><% if client.billing_start_date.year == 2015 %><% calc = (((2016 * 12 + 1) - (client.billing_start_date.year * 12 + client.billing_start_date.month)) * client.price.cost) %><% partial_rev_2015 += calc %><% calc %><% end %><% if (client.billing_start_date.year == 2015) %><%= (partial_rev_2015) %><% end %></Data></Cell>
          <Cell><Data ss:Type="Number"><% if client.billing_start_date.year == 2014 %><% full_rev_2014 = 0 %><% full_rev_2014 = (client.price.cost * 12) %><%= (full_rev_2014) %><% elsif client.billing_start_date.year == 2015 %><% partial_rev_2015 = 0 %><% calc = (((2016 * 12 + 1) - (client.billing_start_date.year * 12 + client.billing_start_date.month)) * client.price.cost) %><% partial_rev_2015 += calc %><% calc %><%= (partial_rev_2015) %><% end %></Data></Cell>
          <Cell><Data ss:Type="String"><%= client.notes %></Data></Cell>
          <Cell><Data ss:Type="String"><%= client.finance_contact_name %></Data></Cell>
          <Cell><Data ss:Type="String"><%= client.finance_contact_email %></Data></Cell>
          <Cell><Data ss:Type="String"><%= client.finance_contact_phone %></Data></Cell>
          <Cell><Data ss:Type="String"><%= client.venue_contact_name %></Data></Cell>
          <Cell><Data ss:Type="String"><%= client.venue_contact_email %></Data></Cell>
          <Cell><Data ss:Type="String"><%= client.venue_contact_phone %></Data></Cell>
        </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/clients/new.html.erb
<div class="container">
<h1>New client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>
</div>

app/views/clients/scratch.html.erb
<% if client.billing_start_date.year == 2014 %>
	<% full_rev_2014 = (client.price.cost * 12) %><% end %>
	<% if client.billing_start_date.year == 2015 %>
	<% calc = (((2016 * 12 + 1) - (client.billing_start_date.year * 12 + client.billing_start_date.month)) * client.price.cost) %><% partial_rev_2015 += calc %><% calc %>
	<% total_rev_2015 = (full_rev_2014 + partial_rev_2015) %>
<%= (total_rev_2015) %>
<% end %>

<% for client.billing_start_date.year == 2014 %><% full_rev_2014 = (client.price.cost * 12) %><% if client.billing_start_date.year == 2015 %><% calc = (((2016 * 12 + 1) - (client.billing_start_date.year * 12 + client.billing_start_date.month)) * client.price.cost) %><% partial_rev_2015 += calc %><% calc %><% total_rev_2015 = (full_rev_2014 + partial_rev_2015) %><%= (total_rev_2015) %><% end %><% end %>

<% if client.billing_start_date.year == 2015 %>
	<% calc = (((2016 * 12 + 1) - (client.billing_start_date.year * 12 + client.billing_start_date.month)) * client.price.cost) %><% partial_rev_2015 += calc %><% calc %>
	<% total_rev_2015 = full_rev_2014 + partial_rev_2015 %>
<%= total_rev_2015 %>
<% end %>

<% partial_rev_2015 = 0 %>
	<% if client.billing_start_date.year == 2015 %>
		<% calc = (((2016 * 12 + 1) - (client.billing_start_date.year * 12 + client.billing_start_date.month)) * client.price.cost) %>
		<% partial_rev_2015 += calc %>
		<% calc %>
	<% end %>
<% if (client.billing_start_date.year == 2015) %>
	<%= (partial_rev_2015) %>
<% end %>

app/views/clients/show.html.erb
<div class="container">

<h1><%= @client.name %></h1>

<p>
  <strong>Kickoff Date:</strong>
  <%= @client.kickoff_date %>
  
</p>

<p>
  <strong>Launch Date:</strong>
  <%= @client.launch_date %>
  
</p>

<p>
  <strong>Billing Start Date:</strong>
  <%= @client.billing_start_date %>
</p>

<p>
  <strong>Division:</strong>
  <%= @client.division.name %>
</p>

<p>
  <strong>Ticketing Provider:</strong>
  <%= @client.ticketing_provider %>
</p>

<p>
  <strong>Internal?:</strong>
  <%= @client.internal %>
</p>

<p>
  <strong>Price:</strong>
  <%= @client.price.name  %> at $<%= @client.price.cost %> per month
</p>

<p>
  <strong>Region:</strong>
  <%= @client.region %>
</p>

<p style="white-space: pre-wrap;">
  <strong>Notes:</strong>
  <%= @client.notes %>
</p>

<% if can? :destroy, @client %>
<p>
  <strong>Delete Client:</strong>
<%= link_to 'Destroy', @client, method: :delete, data: { confirm: 'Are you sure?' } %>
</p>
<% end %>


<% if can? :edit, @client %>
<%= link_to 'Edit', edit_client_path(@client) %> |
<% end %>
<%= link_to 'Back', clients_path %>
</div>