config/routes.rb
Rollout::Application.routes.draw do
  resources :logs

  resources :divisions

  resources :changes

  resources :launches

  resources :prices

  resources :clients

  root :to => "clients#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/launch.rb
# == Schema Information
#
# Table name: launches
#
#  id         :integer          not null, primary key
#  beta       :boolean
#  betadate   :datetime
#  startdate  :datetime
#  created_at :datetime
#  updated_at :datetime
#

class Launch < ActiveRecord::Base
	belongs_to :client
end

app/controllers/launches_controller.rb
class LaunchesController < ApplicationController
  before_action :set_launch, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /launches
  # GET /launches.json
  def index
    @launches = Launch.all
  end

  # GET /launches/1
  # GET /launches/1.json
  def show
  end

  # GET /launches/new
  def new
    @launch = Launch.new
  end

  # GET /launches/1/edit
  def edit
  end

  # POST /launches
  # POST /launches.json
  def create
    @launch = Launch.new(launch_params)

    respond_to do |format|
      if @launch.save
        format.html { redirect_to @launch, notice: 'Launch was successfully created.' }
        format.json { render action: 'show', status: :created, location: @launch }
      else
        format.html { render action: 'new' }
        format.json { render json: @launch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /launches/1
  # PATCH/PUT /launches/1.json
  def update
    respond_to do |format|
      if @launch.update(launch_params)
        format.html { redirect_to @launch, notice: 'Launch was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @launch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /launches/1
  # DELETE /launches/1.json
  def destroy
    @launch.destroy
    respond_to do |format|
      format.html { redirect_to launches_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_launch
      @launch = Launch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def launch_params
      params.require(:launch).permit(:beta, :betadate, :startdate)
    end
end

app/helpers/launches_helper.rb
module LaunchesHelper
end

app/views/launches/_form.html.erb
<%= simple_form_for(@launch) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :beta %>
    <%= f.input :betadate %>
    <%= f.input :startdate %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/launches/edit.html.erb
<h1>Editing launch</h1>

<%= render 'form' %>

<%= link_to 'Show', @launch %> |
<%= link_to 'Back', launches_path %>

app/views/launches/index.html.erb
<h1>Listing launches</h1>

<table>
  <thead>
    <tr>
      <th>Beta</th>
      <th>Betadate</th>
      <th>Startdate</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @launches.each do |launch| %>
      <tr>
        <td><%= launch.beta %></td>
        <td><%= launch.betadate %></td>
        <td><%= launch.startdate %></td>
        <td><%= link_to 'Show', launch %></td>
        <td><%= link_to 'Edit', edit_launch_path(launch) %></td>
        <td><%= link_to 'Destroy', launch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Launch', new_launch_path %>

app/views/launches/new.html.erb
<h1>New launch</h1>

<%= render 'form' %>

<%= link_to 'Back', launches_path %>

app/views/launches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Beta:</strong>
  <%= @launch.beta %>
</p>

<p>
  <strong>Betadate:</strong>
  <%= @launch.betadate %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @launch.startdate %>
</p>

<%= link_to 'Edit', edit_launch_path(@launch) %> |
<%= link_to 'Back', launches_path %>