config/routes.rb
Rollout::Application.routes.draw do
  resources :logs

  resources :divisions

  resources :changes

  resources :launches

  resources :prices

  resources :clients

  root :to => "clients#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/price.rb
# == Schema Information
#
# Table name: prices
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  cost       :integer
#  created_at :datetime
#  updated_at :datetime
#

class Price < ActiveRecord::Base
	has_many :clients
	has_paper_trail
	resourcify
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :set_price, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /prices
  # GET /prices.json
  def index
    @prices = Price.all
    @user = current_user
  end

  # GET /prices/1
  # GET /prices/1.json
  def show
  end

  # GET /prices/new
  def new
    @price = Price.new
    @user = current_user
  end

  # GET /prices/1/edit
  def edit
    @price = Price.find(params[:id])
    @user = current_user
  end

  # POST /prices
  # POST /prices.json
  def create
    @price = Price.new(price_params)
    @user = current_user

    respond_to do |format|
      if @price.save
        format.html { redirect_to @price, notice: 'Price was successfully created.' }
        format.json { render action: 'show', status: :created, location: @price }
      else
        format.html { render action: 'new' }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prices/1
  # PATCH/PUT /prices/1.json
  def update
    respond_to do |format|
      if @price.update(price_params)
        format.html { redirect_to @price, notice: 'Price was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @price.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prices/1
  # DELETE /prices/1.json
  def destroy
    @price.destroy
    respond_to do |format|
      format.html { redirect_to prices_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price
      @price = Price.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def price_params
      params.require(:price).permit(:name, :cost)
    end
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/views/prices/_form.html.erb
<%= simple_form_for(@price) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :cost %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/prices/edit.html.erb
<h1>Editing price</h1>

<%= render 'form' %>

<%= link_to 'Show', @price %> |
<%= link_to 'Back', prices_path %>

app/views/prices/index.html.erb
<div class="containter">
<h1>Advantage Prices</h1>


<table class="table table-striped table-responsive">
    <tr class="row">
    <td>
        <div class="col-xs-3">
          Price Name
        </div>
        <div class="col-xs-2">
          Cost Per Month
        </div>
        <div class="col-xs-7">
          Show
          <% if can? :edit, @client %>
          /Edit/Delete
          <% end %>
        </div>
      </td>
    </tr>

    <% @prices.each do |price| %>
        <tr class="row"><td>
            <div class="col-xs-3"><%= link_to "#{price.name}", price %></div>
            <div class="col-xs-2">
              $<%= price.cost %>
            </div>
              <div class="btn-group text-right col-xs-7">
                <button type="button" class="btn btn-default btn-xs">
                  <%= link_to '<span class="glyphicon glyphicon-eye-open"></span>' .html_safe, price %>
                </button>
                <% if can? :edit, @client %>
                <button type="button" class="btn btn-default btn-xs">
                  <%= link_to '<span class="glyphicon glyphicon-edit"></span>' .html_safe, edit_price_path(price) %>
                </button>
                <% end %>
                <% if can? :destroy, @client %>
                <button type="button" class="btn btn-default btn-xs">
                  <%= link_to '<span class="glyphicon glyphicon-trash"></span>' .html_safe, price, method: :delete, data: { confirm: 'Are you sure?' } %>
                </button>
                <% end %>
              </div>
        </td></tr>
      <% end %>

</table>


<br>
<% if can? :new, @price %>
<%= link_to 'New Price', new_price_path %>
<% end %>
</div>

app/views/prices/new.html.erb
<h1>New price</h1>

<%= render 'form' %>

<%= link_to 'Back', prices_path %>

app/views/prices/show.html.erb
<div class="container">
<h1><%= @price.name %></h1>

<p>
  <strong>Cost:</strong>
  $<%= @price.cost %> per month
</p>

<% if can? :edit, @price %>
<%= link_to 'Edit', edit_price_path(@price) %> |
<% end %>
<%= link_to 'Back', prices_path %>

</div>